// Entrypoint for R package
// This file is generated by extendr and should not be edited

#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

// Forward declarations for Rust functions
SEXP wrap__lbug_connect(SEXP path);
SEXP wrap__lbug_execute(SEXP conn, SEXP query);
SEXP wrap__lbug_shutdown(SEXP conn);
SEXP wrap__lbug_is_available(void);

// Registration of native routines
static const R_CallMethodDef CallEntries[] = {
    {"wrap__lbug_connect",       (DL_FUNC) &wrap__lbug_connect,       1},
    {"wrap__lbug_execute",       (DL_FUNC) &wrap__lbug_execute,       2},
    {"wrap__lbug_shutdown",      (DL_FUNC) &wrap__lbug_shutdown,      1},
    {"wrap__lbug_is_available",  (DL_FUNC) &wrap__lbug_is_available,  0},
    {NULL, NULL, 0}
};

void R_init_lbugr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
