# Generated by extendr: Do not edit by hand
#
# This file contains R wrapper functions for the Rust backend

#' @useDynLib lbugr, .registration = TRUE
NULL

#' Connect to a Ladybug database
#' @param path Path to the database (use ":memory:" for in-memory)
#' @return An external pointer to the connection
#' @keywords internal
lbug_connect <- function(path) {
  .Call(wrap__lbug_connect, path)
}

#' Execute a Cypher query
#' @param conn Connection object from lbug_connect
#' @param query Cypher query string
#' @return A data.frame with query results
#' @keywords internal
lbug_execute <- function(conn, query) {
  .Call(wrap__lbug_execute, conn, query)
}

#' Shutdown a database connection
#' @param conn Connection object to shutdown
#' @keywords internal
lbug_shutdown <- function(conn) {
  invisible(.Call(wrap__lbug_shutdown, conn))
}

#' Check if the Rust library is available
#' @return Logical indicating availability
#' @keywords internal
lbug_is_available <- function() {
  .Call(wrap__lbug_is_available)
}
