# Generated by extendr for the lbugr package.
# Do not edit by hand.

#' @rdname lbug_connect
#' @export
lbug_connect <- function(path) {
  .Call("_lbugr_lbug_connect", PACKAGE = "lbugr", path)
}

#' @rdname lbug_execute
#' @export
lbug_execute <- function(conn, query) {
  .Call("_lbugr_lbug_execute", PACKAGE = "lbugr", conn, query)
}

#' @rdname lbug_shutdown
#' @export
lbug_shutdown <- function(conn) {
  .Call("_lbugr_lbug_shutdown", PACKAGE = "lbugr", conn)
}

#' @rdname lbug_is_available
#' @export
lbug_is_available <- function() {
  .Call("_lbugr_lbug_is_available", PACKAGE = "lbugr")
}
